-- 写出下列应用对应的SQL语句，并将查询语句定义为视图。视图名根据题号依次命名为V38,V41,V44。
-- 38) 列出英语系与数学系的教师的姓名与 工资，并按姓名排序。
-- 41) 列出所有姓名以"武"开头且只有3个字的学生的学号、姓名与所在班级，并按姓名排序
-- 44) 列出2017年下学期选修了CS013号课程却没有及格的学生的学号及其成绩，并按学号排序。
CREATE VIEW V38 AS
SELECT
    INSTRUCTOR.NAME,
    INSTRUCTOR.SALARY
FROM
    INSTRUCTOR
WHERE
    INSTRUCTOR.DEPT_NAME IN ('English', 'Mathematics')
ORDER BY
    INSTRUCTOR.NAME;

CREATE VIEW V41 AS
SELECT
    STUDENT.ID,
    STUDENT.NAME,
    CLASS.CLASS_NAME
FROM
    STUDENT
    JOIN CLASS ON STUDENT.STU_CLASS = CLASS.CLASS_NAME
WHERE
    STUDENT.NAME LIKE '武__'
    AND LENGTH(STUDENT.NAME) = 3
ORDER BY
    STUDENT.NAME;

CREATE VIEW V44 AS
SELECT
    TAKES.ID,
    TAKES.GRADE
FROM
    TAKES
WHERE
    TAKES.COURSE_ID = 'CS013'
    AND TAKES.SEC_ID LIKE '%02'
    AND TAKES.SEMESTER = 'Fall'
    AND TAKES.YEAR = 2017
    AND TAKES.GRADE < 60
ORDER BY
    TAKES.ID;