-- 写出下列应用对应的SQL语句，并将查询语句定义为视图。视图名根据题号依次命名为V47,V50,V53,V56,V59。
-- 47) 查询软件工程专业2016年毕业的学生的学号和姓名，并按学号排序。
-- 50) 查询2017年选修了CS001号课程且学号最后两位为“27”的学生的学号、姓名，以及课程名称及成绩，按学号排序。
-- 53) 查询2018年上学期PH001号课程考试成绩不及格的学生的学号与姓名，按学号排序。
-- 56) 查询2018年上学期计算机系没有上课的教师名单，按姓名排序。
-- 59) 查询2018年上学期同时选修了G0001号和PH001课程的学生的学号和班级，按学号排序。
CREATE VIEW V47 AS
SELECT
    STUDENT.ID,
    STUDENT.NAME
FROM
    STUDENT
WHERE
    STUDENT.MAJOR = 'Software Engineering'
    AND STUDENT.GRAD_YEAR = 2016
ORDER BY
    STUDENT.ID;

CREATE VIEW V50 AS
SELECT
    TAKES.ID,
    STUDENT.NAME,
    COURSE.TITLE,
    TAKES.GRADE
FROM
    TAKES
    JOIN STUDENT ON TAKES.ID = STUDENT.ID
    JOIN COURSE ON TAKES.COURSE_ID = COURSE.COURSE_ID
WHERE
    TAKES.COURSE_ID = 'CS001'
    AND TAKES.ID LIKE '%27'
    AND TAKES.YEAR = 2017
ORDER BY
    TAKES.ID;

CREATE VIEW V53 AS
SELECT
    TAKES.ID,
    STUDENT.NAME
FROM
    TAKES
    JOIN STUDENT ON TAKES.ID = STUDENT.ID
WHERE
    TAKES.COURSE_ID = 'PH001'
    AND TAKES.SEC_ID = '01'
    AND TAKES.SEMESTER = 'Fall'
    AND TAKES.YEAR = 2018
    AND TAKES.GRADE < 60
ORDER BY
    TAKES.ID;

CREATE VIEW V56 AS
SELECT
    INSTRUCTOR.NAME
FROM
    INSTRUCTOR
WHERE
    INSTRUCTOR.DEPT_NAME = 'Computer Science'
    AND NOT EXISTS (
        SELECT
            *
        FROM
            SECTION
        WHERE
            SECTION.INSTRUCTOR_ID = INSTRUCTOR.ID
            AND SECTION.SEMESTER = 'Fall'
            AND SECTION.YEAR = 2018
    )
ORDER BY
    INSTRUCTOR.NAME;

CREATE VIEW V59 AS
SELECT
    TAKES.ID,
    STUDENT.STU_CLASS
FROM
    TAKES
    JOIN STUDENT ON TAKES.ID = STUDENT.ID
WHERE
    TAKES.COURSE_ID IN ('G0001', 'PH001')
    AND TAKES.SEMESTER = 'Fall'
    AND TAKES.YEAR = 2018
GROUP BY
    TAKES.ID,
    STUDENT.STU_CLASS
HAVING
    COUNT(*) = 2
ORDER BY
    TAKES.ID;