ALTER TABLE "COUNTRIES" ADD CONSTRAINT "PK_COUNTRIES" PRIMARY KEY ("CID");
ALTER TABLE "DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPTNO");
ALTER TABLE "DEPT" ADD CONSTRAINT "FK_DEPT_COUNTRIES" FOREIGN KEY ("CID") REFERENCES "A202105961404"."COUNTRIES" ("CID") ON DELETE CASCADE;
ALTER TABLE "EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY ("EMPNO");
ALTER TABLE "EMP" ADD CONSTRAINT "FK_EMP_DEPT" FOREIGN KEY ("DEPTNO") REFERENCES "A202105961404"."DEPT" ("DEPTNO") ON DELETE CASCADE;