INSERT INTO A202105961404.DEPT (DEPTNO,DNAME,CID,LOC,EMPS,INCOME) VALUES
	 (10,'ACCOUNTING','US','New York',NULL,NULL),
	 (20,'RESEARCH','CN','Shanghai',NULL,NULL),
	 (30,'SALES','CA','Toronto',NULL,NULL),
	 (40,'OPERATIONS','FR','Paris',NULL,NULL),
	 (10,'ACCOUNTING','US','New York',NULL,NULL),
	 (20,'RESEARCH','CN','Shanghai',NULL,NULL),
	 (30,'SALES','CA','Toronto',NULL,NULL),
	 (40,'OPERATIONS','FR','Paris',NULL,NULL);
